export enum ActivityAction {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CREATE_WALLET = 'CREATE_WALLET',
  UPDATE_WALLET = 'UPDATE_WALLET',
  DELETE_WALLET = 'DELETE_WALLET',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
}